# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import ring_transfer_pb2 as ring__transfer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ring_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RingTransferStub(object):
    """Bidirectional streaming for the Ring All-Gather data plane.
    Each node opens a single gRPC bidirectional stream to its right neighbor
    and accepts one from its left neighbor. Chunks flow in one direction
    around the logical ring for exactly N-1 hops.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChunks = channel.stream_stream(
                '/ring_transfer.RingTransfer/StreamChunks',
                request_serializer=ring__transfer__pb2.Chunk.SerializeToString,
                response_deserializer=ring__transfer__pb2.Ack.FromString,
                _registered_method=True)


class RingTransferServicer(object):
    """Bidirectional streaming for the Ring All-Gather data plane.
    Each node opens a single gRPC bidirectional stream to its right neighbor
    and accepts one from its left neighbor. Chunks flow in one direction
    around the logical ring for exactly N-1 hops.
    """

    def StreamChunks(self, request_iterator, context):
        """StreamChunks is a bidirectional streaming RPC.
        The sender pushes Chunk messages; the receiver may send Ack messages
        for flow control.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RingTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChunks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamChunks,
                    request_deserializer=ring__transfer__pb2.Chunk.FromString,
                    response_serializer=ring__transfer__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ring_transfer.RingTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ring_transfer.RingTransfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RingTransfer(object):
    """Bidirectional streaming for the Ring All-Gather data plane.
    Each node opens a single gRPC bidirectional stream to its right neighbor
    and accepts one from its left neighbor. Chunks flow in one direction
    around the logical ring for exactly N-1 hops.
    """

    @staticmethod
    def StreamChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ring_transfer.RingTransfer/StreamChunks',
            ring__transfer__pb2.Chunk.SerializeToString,
            ring__transfer__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
