# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ring_transfer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ring_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ring_transfer.proto\x12\rring_transfer\"\x8c\x01\n\x05\x43hunk\x12\x13\n\x0b\x63hunk_bytes\x18\x01 \x01(\x0c\x12\x15\n\roriginator_ip\x18\x02 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x03 \x01(\x05\x12\x12\n\nhops_taken\x18\x04 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x05 \x01(\x05\x12\x1b\n\x13\x64\x65\x61\x64_nodes_detected\x18\x06 \x03(\t\">\n\x03\x41\x63k\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2L\n\x0cRingTransfer\x12<\n\x0cStreamChunks\x12\x14.ring_transfer.Chunk\x1a\x12.ring_transfer.Ack(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ring_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=39
  _globals['_CHUNK']._serialized_end=179
  _globals['_ACK']._serialized_start=181
  _globals['_ACK']._serialized_end=243
  _globals['_RINGTRANSFER']._serialized_start=245
  _globals['_RINGTRANSFER']._serialized_end=321
# @@protoc_insertion_point(module_scope)
