# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ring.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nring.proto\x12\x03\x64\x66l\"\x86\x01\n\x0cModelPayload\x12\x15\n\roriginator_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0b\n\x03hop\x18\x03 \x01(\x05\x12\x0b\n\x03ttl\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x12\n\ndead_nodes\x18\x06 \x03(\t\x12\x14\n\x0c\x64\x61taset_size\x18\x07 \x01(\x05\"/\n\x08ModelAck\x12\x13\n\x0breceiver_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2=\n\x0cRingTransfer\x12-\n\tSendModel\x12\x11.dfl.ModelPayload\x1a\r.dfl.ModelAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELPAYLOAD']._serialized_start=20
  _globals['_MODELPAYLOAD']._serialized_end=154
  _globals['_MODELACK']._serialized_start=156
  _globals['_MODELACK']._serialized_end=203
  _globals['_RINGTRANSFER']._serialized_start=205
  _globals['_RINGTRANSFER']._serialized_end=266
# @@protoc_insertion_point(module_scope)
